repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: psf/black
    -   id: astral-sh/ruff-pre-commit
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format